# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TtXU6AWROcvPcCmQISt1U1tIJDFVxD6q
"""

import numpy as np
import pandas as pd
import sys
import matplotlib.pyplot as plt

from collections import OrderedDict
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier

n_samples = int(sys.argv[1]);
n_attr = int(sys.argv[2]);

print(n_samples)
X, y = make_classification(
    n_samples=n_samples,  # row number
    n_features=n_attr, # feature numbers
    n_informative=8, # The number of informative features
    n_redundant = 0, # The number of redundant features
    n_repeated = 0, # The number of duplicated features
    n_classes = 2, # The number of classes
    random_state = 42 # random seed
)

X_data = np.array(X)
y_data = np.array(y)
new_data = np.append(X_data ,y_data.reshape(-1,1),axis=1)

df = pd.DataFrame(new_data)
df.head()

df.to_csv("build/src/dummy_dataset"+str(n_samples)+".csv",index=False)

